/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   iamerror.h                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mrosario <mrosario@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/03/02 16:29:20 by mrosario          #+#    #+#             */
/*   Updated: 2020/08/18 17:50:05 by mrosario         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef I_AM_ERROR_H
# define I_AM_ERROR_H

#define REDERROR RED"\nError\n"RESET
#define	YELLOWERROR YELLOW"\nError\n"RESET
#define cubFileNotFound RED"FILE NOT FOUND, CHECK YOUR .CUB FILE PATH\n"RESET
#define weirdFD RED"YOUR GAME IS TRYING TO READ FROM STDIN, STDOUT OR STDERR... I DON'T KNOW WHAT TO SAY... THIS SHOULD NOT BE HAPPENING O_O\n"RESET
#define couldNotClose YELLOW"ONE OR MORE FILES COULD NOT BE CLOSED\n"RESET
#define mallocFail RED"MEMORY ALLOCATION FAILURE; CHECK YOUR AVAILABLE MEMORY AND REDUCE YOUR CUB FILE SIZE\n"RESET
#define getResFail YELLOW"INVALID RESOLUTION; CHECK YOUR MAP FILE; USING DEFAULT RESOLUTION\n"RESET
#define badResSyn YELLOW"BAD RESOLUTION SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define badResSize YELLOW"PROVIDED SCREEN RESOLUTION TOO SMALL (BELOW 240) OR TOO LARGE (ABOVE DISPLAY RESOLUTION)\n"RESET
#define getNOFail RED"NORTH WALL (NO) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define	badNOSyn RED"BAD NORTH WALL SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define pathNOFail RED"NORTH WALL TEXTURE FILE (NO) DOES NOT EXIST AT THE PATH YOU SPECIFIED:\n"RESET
#define getSOFail RED"SOUTH WALL (SO) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define badSOSyn RED"BAD SOUTH WALL SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define pathSOFail RED"SOUTH WALL TEXTURE FILE (SO) DOES NOT EXIST AT THE PATH YOU SPECIFIED:\n"RESET
#define getWEFail RED"WEST WALL (WE) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define badWESyn RED"BAD WEST WALL SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define pathWEFail RED"WEST WALL TEXTURE FILE (WE) DOES NOT EXIST AT THE PATH YOU SPECIFIED:\n"RESET
#define getEAFail RED"EAST WALL (EA) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define badEASyn RED"BAD EAST WALL SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define pathEAFail RED"EAST WALL TEXTURE FILE (EA) DOES NOT EXIST AT THE PATH YOU SPECIFIED:\n"RESET
#define getSprFail RED"SPRITE (S) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define badSprSyn RED"BAD SPRITE TEXTURE SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define pathSprFail RED"SPRITE TEXTURE FILE (S) DOES NOT EXIST AT THE PATH YOU SPECIFIED:\n"RESET
#define texSizeFail YELLOW"TEXTURE SIZE NOT FOUND; MAKE SURE YOU ARE USING XPM FILES, *NOT* XPM2 OR XPM3\nDEFAULTING TO 64; YOUR IMAGE MAY NOT DISPLAY CORRECTLY!!\n"RESET
#define wallTexSizeDif RED"DIFFERENT WALL TEXTURE SIZES! YOUR WALL TEXTURE SIZES MUST ALL BE THE SAME BY ORDER OF\nUN SECURITY COUNCIL; ABORTING PROGRAM\n"RESET
#define sprTexSizeFail YELLOW"SPRITE TEXTURE SIZE NOT FOUND; MAKE SURE YOU ARE USING XPM FILES, *NOT* XPM2 OR XPM3\nYOUR IMAGE MAY NOT DISPLAY CORRECTLY!!\n"RESET
#define	couldNotOpenXPM RED"UNABLE TO OPEN THIS XPM FILE; CHECK YOUR MEMORY AVAILABILITY\n"RESET
#define FColorInvalid YELLOW"INVALID FLOOR COLOR; USING DEFAULT COLOR\n"RESET
#define badFColorSyn YELLOW"BAD FLOOR COLOR SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define CColorInvalid YELLOW"INVALID CEILING COLOR; USING DEFAULT COLOR\n"RESET
#define badCColorSyn YELLOW"BAD CEILING COLOR SYNTAX; FOLLOW THE INSTRUCTIONS IN README.TXT\n"RESET
#define outOfBounds RED"THE PLAYER CHARACTER (NSEW) MUST BE IN AN AREA BOUNDED BY WALLS; CHECK YOUR MAP FILE\n"RESET
#define noMapFound RED"MAP NOT FOUND\n"RESET
#define badMap3line RED"INVALID MAP: THE MAP MUST HAVE AT LEAST THREE LINES TO CREATE A BOUNDED AREA\n"RESET
#define noPlayer RED"INVALID MAP: NO PLAYER FOUND; MAP MUST HAVE A PLAYER STARTING LOCATION\n"RESET
#define tooManyPlayers RED"INVALID MAP: MULTIPLE PLAYERS FOUND; MAP MAY ONLY HAVE ONE PLAYER STARTING LOCATION\n"RESET
#define getNextLineFail RED"GET NEXT LINE FAILED; BLAME YOUR DEVELOPER FOR THIS INDIGNITY\n"RESET
#define	mapTooBig RED"REALLY? YOU REALLY NEED A MAP THAT GIGANTIC? IT'S OVER  BYTES! I DON'T THINK SO. MAKE YOUR MAP SMALLER.\n"RESET
#endif