/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   iamerror.h                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mrosario <mrosario@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/03/02 16:29:20 by mrosario          #+#    #+#             */
/*   Updated: 2020/08/27 19:41:44 by mrosario         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef I_AM_ERROR_H
# define I_AM_ERROR_H

#define CUBNOTFOUND RED"Error\nCHECK YOUR .CUB FILE PATH\n"RESET
#define WEIRDFD RED"Error\nYOUR GAME IS TRYING TO READ FROM STDIN, STDOUT OR STDERR... THIS SHOULD NOT BE HAPPENING O_O\n"RESET
#define COULDNOTCLOSE RED"Error\nFILE COULD NOT CLOSE\n"RESET
#define MALLOCFAIL RED"Error\nMEMORY ALLOCATION FAILURE; CHECK YOUR AVAILABLE MEMORY\n"RESET
#define GETRESFAIL YELLOW"Error\nINVALID RESOLUTION; CHECK YOUR MAP FILE; SWITCHING TO DEFAULT RESOLUTION\n"RESET
#define BADRESSYN YELLOW"Error\nUSE ONLY 'R' OR 'r' SPECIFIER TO PASS SCREEN RESOLUTION; CHECK YOUR MAP FILE\n"RESET
#define GETNOFAIL RED"Error\nNORTH WALL (NO) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define PATHNOFAIL RED"Error\nNORTH WALL FILE (NO) DOES NOT EXIST AT SPECIFIED PATH; SEE QUANTUM PATH INFO AND CHECK YOUR MAP FILE\n"RESET
#define GETSOFAIL RED"Error\nSOUTH WALL (SO) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define PATHSOFAIL RED"Error\nSOUTH WALL FILE (SO) DOES NOT EXIST AT SPECIFIED PATH; SEE QUANTUM PATH INFO AND CHECK YOUR MAP FILE\n"RESET
#define GETWEFAIL RED"Error\nWEST WALL (WE) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define PATHWEFAIL RED"Error\nWEST WALL FILE (WE) DOES NOT EXIST AT SPECIFIED PATH; SEE QUANTUM PATH INFO AND CHECK YOUR MAP FILE\n"RESET
#define GETEAFAIL RED"Error\nEAST WALL (EA) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define PATHEAFAIL RED"Error\nEAST WALL FILE (EA) DOES NOT EXIST AT SPECIFIED PATH; SEE QUANTUM PATH INFO AND CHECK YOUR MAP FILE\n"RESET
#define GETSPRFAIL RED"Error\nSPRITE (S) TEXTURE FILE PATH RETRIEVAL FAILED; CHECK YOUR MAP FILE\n"RESET
#define PATHSPRFAIL RED"Error\nSPRITE FILE (S) DOES NOT EXIST AT SPECIFIED PATH; SEE QUANTUM PATH INFO AND CHECK YOUR MAP FILE\n"RESET
#define WALLTEXSIZEFail YELLOW"Error\nWALL TEXTURE SIZE NOT FOUND, DEFAULTING TO 64; YOUR IMAGE MAY NOT DISPLAY CORRECTLY!!\n"RESET
#define WALLTEXSIZEDIF RED"Error\nDIFFERENT WALL TEXTURE SIZES! YOUR WALL TEXTURE SIZES MUST ALL BE THE SAME BY ORDER OF UN SECURITY COUNCIL; ABORTING PROGRAM\n"RESET
#define sprTexSizeFail YELLOW"Error\nSPRITE TEXTURE SIZE NOT FOUND, DEFAULTING TO 64; YOUR IMAGE MAY NOT DISPLAY CORRECTLY!!\n"RESET
#define FCOLORINVALID YELLOW"Error\nINVALID FLOOR COLOR; USING DEFAULT COLOR\n"RESET
#define BADFCOLORSYN YELLOW"Error\nUSE ONLY 'F' OR 'f' SPECIFIER TO PASS FLOOR COLOR; CHECK YOUR MAP FILE\n"RESET
#define CCOLORINVALID YELLOW"Error\nINVALID CEILING COLOR; USING DEFAULT COLOR\n"RESET
#define BADCCOLORSYN YELLOW"Error\nUSE ONLY 'C' OR 'c' SPECIFIER TO PASS CEILING COLOR; CHECK YOUR MAP FILE\n"RESET
#define OUTOFBOUNDS RED"Error\nTHE PLAYER CHARACTER (NSEW) MUST BE IN AN AREA BOUNDED BY WALLS\n"RESET
#define BADMAP3LINE RED"Error\nINVALID MAP: THE MAP MUST HAVE AT LEAST THREE LINES TO CREATE A BOUNDED AREA\n"RESET
#define NOPLAYER RED"Error\nINVALID MAP: NO PLAYER FOUND; MAP MUST HAVE PLAYER STARTING LOCATION\n"RESET
#define TOOMANYPLAYERS RED"Error\nINVALID MAP: MULTIPLE PLAYERS FOUND; MAP MAY ONLY HAVE ONE PLAYER STARTING LOCATION\n"RESET

#endif